###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: fgt-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: fgt-mailhog
      ports:
        - "8089:8025"

    mysql:
      image: mysql:5.6
      container_name: fgt-mysql
      working_dir: /application
      volumes:
        - .:/application
        - dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=fgt_db
        - MYSQL_USER=fgt_dbu
        - MYSQL_PASSWORD=fgt
      ports:
        - "8090:3306"

    webserver:
      image: nginx:alpine
      container_name: fgt-webserver
      depends_on:
        - php-fpm
      working_dir: /application
      volumes:
          - .:/application
          - ./tools/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8088:80"

    php-fpm:
      build: tools/phpdocker/php-fpm
      container_name: fgt-php-fpm
      working_dir: /application
      depends_on:
        - mysql
      volumes:
        - .:/application
        - ./tools/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

volumes:
  dbdata: