services:
#    fam_gen_tree_admin.example:
#        class: FamGenTree\AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  fgt_admin:
    class: FamGenTree\AppBundle\Context\Configuration\Infrastructure\ConfigRepository
    arguments: ['@service_container']
