fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fam_gene_tree_setup:
    path:   /setup/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /app_setup.php
        permanent: false

fam_gen_tree_app:
    resource: "@FamGenTreeAppBundle/Resources/config/routing.yml"
    prefix:   /

fam_gen_tree_admin:
    resource: "@FamGenTreeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

