fgt_homepage:
    path:     /
    defaults: { _controller: FamGenTreeAppBundle:Welcome:index }

_fgt_login:
    path:   /login
    defaults: { _controller: FamGenTreeAppBundle:Auth:login }

_fgt_logout:
    path:   /logout
    defaults: { _controller: FamGenTreeAppBundle:Auth:logout }

fgt_dashboard:
    path:   /dashboard
    defaults: { _controller: FamGenTreeAppBundle:Dashboard:index }